internship/src/navigators/main-navigator.tsx, internship/src/screens/ThanhDP/screens/View/BT2.tsx, internship/src/screens/ThanhDP/screens/View/BT5.tsx, internship/src/screens/ThanhDP/screens/View/BT7.tsx
**Bài tập 2: tạo giao diện như hình vẽ và tái sử dụng code bài tập 1**
Before | After
-- | --
https://user-images.githubusercontent.com/118170113/204426499-dbcdec86-1a5c-4ec0-961f-f35bf0b9e31b.mp4
=> ThanhDP/  Bài tập 2 Tạo giao diện như hình vẽ Evidence Before After

internship/package-lock.json, internship/src/navigators/main-navigator.tsx, internship/src/screens/ThanhDP/screens/View/SliderHorizontal.js, internship/src/screens/ThanhDP/screens/View/SliderVertical.js, internship/yarn.lock
**Bài tập 5: tạo Slider**
**BEFORE**
**AFTER**
https://user-images.githubusercontent.com/118170113/206076171-d30bf8b4-0a28-4636-9cbf-146c9f793f05.mp4
https://user-images.githubusercontent.com/118170113/206076184-339aa69b-1056-4891-90ee-04ffabb06452.mp4
=> @thanhdp/feat/baitap5

internship/src/navigators/main-navigator.tsx, internship/src/screens/ThanhDP/screens/Layout/BT1.tsx
**Bài tập 1/ Phần layout:**
**BEFORE**
**AFTER**
https://user-images.githubusercontent.com/118170113/206080420-ec8d9c42-f18a-4dda-85ee-ea9151c38652.mp4
=> @thanhdp/feat/layout/baitap1

internship/src/navigators/main-navigator.tsx, internship/src/screens/ThanhDP/screens/Layout/BT11.tsx
**Bài tập 11**
**BEFORE**
**AFTER**
https://user-images.githubusercontent.com/118170113/206084138-4cd7c1e8-911c-4393-8824-5aee9272903d.mp4
=> @thanhdp/feat/layout/baitap11

internship/src/navigators/main-navigator.tsx, internship/src/screens/ThanhDP/screens/Layout/BT3.tsx
**Bài tập 3**
**BEFORE**
**AFTER**
https://user-images.githubusercontent.com/118170113/206090484-1b8d8144-e005-499a-a3c7-334c866b5bb5.mp4
=> @thanhdp/feat/layout/baitap3

internship/src/navigators/main-navigator.tsx, internship/src/screens/ThanhDP/screens/Layout/BT33.tsx
**Bài tập 3'**
**EVIDENCE**
**BEFORE**
**AFTER**
https://user-images.githubusercontent.com/118170113/206091124-142adb52-0822-4f3a-8dc9-fec629f8ac65.mp4
=> @thanhdp/feat/layout/baitap33

internship/src/navigators/main-navigator.tsx, internship/src/screens/ThanhDP/screens/Layout/BT333.tsx
**Bài tập 333**
**BEFORE**
**AFTER**
https://user-images.githubusercontent.com/118170113/206108521-ba7bc135-840f-4d30-9398-5c9b767fe587.mp4
=> @thanhdp/feat/layout/baitap333

internship/src/navigators/main-navigator.tsx, internship/src/screens/ThanhDP/screens/Layout/BT4.tsx
**Bài tập 4**
**BEFORE**
**AFTER**
https://user-images.githubusercontent.com/118170113/206112084-581f6928-092c-485b-93d3-6f2c3e962811.mp4
=> @thanhdp/feat/layout/baitap4

internship/src/navigators/main-navigator.tsx, internship/src/screens/ThanhDP/screens/Layout/BT44.tsx
**Bài tập 44**
**BEFORE**
**AFTER**
https://user-images.githubusercontent.com/118170113/206113497-1f7d13b1-5722-42c3-b715-541f5077db94.mp4
=> @thanhdp/feat/layout/baitap44

internship/src/navigators/main-navigator.tsx, internship/src/screens/ThanhDP/screens/Layout/BT444.tsx
**Bài tập 444**
**BEFORE**
**AFTER**
https://user-images.githubusercontent.com/118170113/206115139-f56f991a-f327-4a3e-8ea4-4129122d0e59.mp4
=> @thanhdp/feat/layout/baitap444

internship/src/navigators/main-navigator.tsx, internship/src/screens/ThanhDP/screens/Layout/BT4444.tsx
**Bài tập 4444**
**BEFORE**
**AFTER**
https://user-images.githubusercontent.com/118170113/206121909-21531b31-bfe6-4713-b0e6-5b4333483418.mp4
=> @thanhdp/feat/layout/baitap4444

internship/src/navigators/main-navigator.tsx, internship/src/screens/ThanhDP/screens/Layout/BT6.tsx
**Bài tập 6**
**BEFORE**
**AFTER**
https://user-images.githubusercontent.com/118170113/206126124-ccd0f5b6-d0ad-4c9b-8226-8bfb822ad7ad.mp4
=> @thanhdp/feat/layout/baitap6

internship/src/navigators/main-navigator.tsx, internship/src/screens/ThanhDP/screens/Layout/BT7.tsx
**BÀI TẬP 7:**
**BEFORE**
**AFTER**
https://user-images.githubusercontent.com/118170113/206134533-8d09656f-bf08-4317-b72a-081666f14637.mp4
=> @thanhdp/feat/layout/baitap7

internship/src/navigators/main-navigator.tsx, internship/src/screens/ThanhDP/screens/Layout/BT8.tsx
**BÀI TẬP 8:**
**BEFORE**
**AFTER**
https://user-images.githubusercontent.com/118170113/206136363-277b2dca-9986-416c-b665-066bce603b04.mp4
=> @thanhdp/feat/layout/baitap8

internship/src/navigators/main-navigator.tsx, internship/src/screens/ThanhDP/screens/Layout/BT9.tsx
**BÀI TẬP 9:**
**BEFORE**
**AFTER**
https://user-images.githubusercontent.com/118170113/206137726-66adecd2-b255-4564-b805-a6057b9f9655.mp4
=> @thanhdp/feat/layout/baitap9

internship/src/navigators/main-navigator.tsx, internship/src/screens/TanPCM/layout/BaiTap1.tsx, internship/yarn.lock
=> (feat): bai tap 1

internship/src/navigators/main-navigator.tsx, internship/src/screens/TanPCM/layout/BaiTap1'.tsx
=> (feat): bai tap 1.1

internship/src/navigators/main-navigator.tsx, internship/src/screens/TanPCM/layout/BaiTap3'.tsx
=> (feat): bai tap 33

internship/src/navigators/main-navigator.tsx, internship/src/screens/TanPCM/layout/BaiTap3''.tsx
=> @tanpcm/feat/layout/baitap333

internship/src/navigators/main-navigator.tsx, internship/src/screens/TanPCM/layout/BaiTap4.tsx
=> (feat): bai tap 4

internship/src/navigators/main-navigator.tsx, internship/src/screens/TanPCM/layout/BaiTap4''.tsx
=> (feat): bai tap 444

internship/src/screens/TanPCM/layout/BaiTap4''''.tsx
=> (feat): bai tap 44444

internship/src/screens/TanPCM/layout/BaiTap5.tsx
=> (feat) : bai tap 5

internship/src/screens/TanPCM/layout/BaiTap5'.tsx
=> (feat) : bai tap 55

internship/src/screens/TanPCM/layout/BaiTap5'''.tsx
=> (feat): bai tap 5555

internship/src/screens/TanPCM/layout/BaiTap5''''.tsx
=> (feat) : bai tao 55555

internship/src/screens/TanPCM/layout/BaiTap6.tsx
=> (feat): bai tap 6

internship/src/screens/TanPCM/layout/BaiTap6''.tsx
=> (feat) : bai tap 666

internship/src/screens/TanPCM/layout/BaiTap6'''.tsx
=> (feat): bai tap 6666

internship/src/screens/TanPCM/layout/BaiTap6''''.tsx
=> (feat): bai tap 66666

internship/src/screens/TanPCM/layout/BaiTap11.tsx
=> (feat): Bai tap so 11

internship/src/screens/TanPCM/layout/BaiTap12.tsx
Before | After
https://user-images.githubusercontent.com/117618328/207219299-5dabe511-f1d0-4b56-81bb-d76801e39940.mov
=> (feat): bai tap 12

internship/src/screens/TanPCM/layout/BaiTap14.tsx
Before | After
https://user-images.githubusercontent.com/117618328/207220041-4351061e-2231-465f-aea3-d4fd8a37e228.mov
=> (feat): Bai tap 14

internship/src/navigators/main-navigator.tsx, internship/src/screens/TanPCM/layout/BaiTap9.tsx
Before | After 
https://user-images.githubusercontent.com/117618328/207215962-a8fc3c1a-8c6b-4689-9c2b-f7a7ead6b350.mov
=> (feat): Bai tap 9

internship/src/navigators/main-navigator.tsx, internship/src/navigators/screens-name.ts, internship/src/screens/TanPCM/Navigation/BaiTap2/Edit.tsx, internship/src/screens/TanPCM/Navigation/BaiTap2/Home.tsx, internship/src/screens/TanPCM/Navigation/BaiTap2/Login.tsx
Before | After
https://user-images.githubusercontent.com/117618328/208345810-362087f3-dfb8-4f40-802f-8482f64211f8.mov
=> [WIP] (feat): bai tap 2 navi

internship/src/screens/TanPCM/layout/BaiTap7B4.tsx
###Bài Tập 7B4: thiết kế như hình theo chiều dọc
Before|After
=> (feat): bai tap 7B4

internship/src/screens/TanPCM/layout/BaiTap7B6''''.tsx
=> (feat): bai tap 7B66666

internship/src/screens/TanPCM/layout/BaiTap7B4''.tsx
=> (feat): bai tap 7b 444

internship/src/screens/TanPCM/layout/BaiTap7B4'''.tsx
=> (feat): bai tap 7B4444

internship/src/screens/TanPCM/layout/BaiTap7B4''''.tsx
=> (feat): bai tap 7B44444

internship/src/screens/TanPCM/layout/BaiTap7B5.tsx
=> (feat): bai tap 7B5

internship/src/screens/TanPCM/layout/BaiTap7B5'.tsx
=> (feat): bai tap 7B55

internship/src/screens/TanPCM/layout/BaiTap7B5''.tsx
=> (feat): bai tap 7B555

internship/src/screens/TanPCM/layout/BaiTap7B5'''.tsx
=> (feat): bai tap 7B5555

internship/src/screens/TanPCM/layout/BaiTap7B5''''.tsx
=> (feat): bai tap 7B55555

internship/src/screens/TanPCM/layout/BaiTap7B6.tsx
=> (feat): bai tap 7B6

internship/src/screens/TanPCM/layout/BaiTap7B6'.tsx
Bài Tập 7B6': thiết kế như hình theo chiều dọc với 5 ô vuông
Before|After
=> (feat): bai tap 7B66

internship/src/screens/TanPCM/layout/BaiTap7B6''.tsx
=> (feat): bai tap 7B666

internship/src/screens/ThanhDP/screens/Navigate/BT2/Edit.tsx, internship/src/screens/ThanhDP/screens/Navigate/BT2/Home.tsx, internship/src/screens/ThanhDP/screens/Navigate/BT2/Login.tsx
* pull
* @thanhdp/feat/navigate/bt2
Co-authored-by: DPT1004 <phuthanhdo104@gmail.com>
=> @thanhdp/feat/navigate/bt2 (#103)
